# Generated by Django 4.2.4 on 2023-09-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pessoa",
            name="nome",
            field=models.CharField(default="", max_length=100),
        ),
    ]
